(def :Alpha,      (BuiltinDomain :Alpha))
(def :Domain,     (BuiltinDomain :Domain     Alpha))
(def :Expression, (BuiltinDomain :Expression Alpha))
(def :Boolean,    (BuiltinDomain :Boolean    Alpha))
(def :Symbol,     (BuiltinDomain :Symbol     Alpha))
(def :String,     (BuiltinDomain :String     Alpha))
(def :Numeric,    (BuiltinDomain :Numeric    Alpha))
(def :Integer,    (BuiltinDomain :Integer    Numeric))
(def :Float,      (BuiltinDomain :Float      Numeric))
(def :Regexp,     (BuiltinDomain :Regexp     Alpha))
(def :Date,       (BuiltinDomain :Date       Alpha))
(def :Time,       (BuiltinDomain :Time       Alpha))
(def :Heading,    (BuiltinDomain :Heading    Alpha))
(def :Module,     (BuiltinDomain :Module     Alpha))
(def :Array,      (ArrayDomain   Alpha))
